flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/images/dog.png
    - lib/assets/images/dogP.png
    - lib/assets/images/Moody.json
    - lib/assets/images/Patas.json
    - lib/assets/images/Doodles.json
    - lib/assets/images/CuteDog.json
    - lib/assets/images/american.jpg
    - lib/assets/images_profile/dog1.jpg
    - lib/assets/images_profile/dog2.jpg
    - lib/assets/images_profile/dog3.jpg
    - lib/assets/images_profile/dog4.jpg
    - lib/assets/images_profile/cat1.jpg
    - lib/assets/images_profile/cat2.jpg
    - lib/assets/images_profile/cat3.jpg
    - lib/assets/images_profile/cat4.jpg

  fonts:
    - family: InknutAntiqua
      fonts:
        - asset: lib/assets/fonts/Inknut_Antiqua/InknutAntiqua-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Inknut_Antiqua/InknutAntiqua-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Inknut_Antiqua/InknutAntiqua-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Inknut_Antiqua/InknutAntiqua-Black.ttf
          weight: 900

    - family: InclusiveSans
      fonts:
        - asset: lib/assets/fonts/InclusiveSans.ttf
          weight: 700
