name: torch_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.2.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/images/dog.png
    - lib/assets/images/dogP.png
    - lib/assets/images/Moody.json
    - lib/assets/images/Patas.json


  fonts:
    - family: InknutAntiqua
      fonts:
        - asset: lib/assets/images/InknutAntiqua-Black.ttf
          weight: 700
        - asset: fonts/Inknut_Antiqua/InknutAntiqua-Regular.ttf
          weight: 400
        - asset: fonts/Inknut_Antiqua/InknutAntiqua-Bold.ttf
          weight: 700
        - asset: fonts/Inknut_Antiqua/InknutAntiqua-SemiBold.ttf
          weight: 600

    - family: InclusiveSans
      fonts:
        - asset: lib/assets/images/InclusiveSans.ttf
          weight: 700
